services:
  app:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8501:8501"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=el_trebol


  database:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: el_trebol
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - ./database/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql